/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LIBRARYMANAGEMENTSYSTEM0_1.Windows;

import LIBRARYMANAGEMENTSYSTEM0_1.Connection.Connections;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Anjana
 */
public class Library_Manegement_System_Strock extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    /**
     * Creates new form Library_Manegement_System_Strock
     */
    public Library_Manegement_System_Strock() {
        initComponents();
        seticon();
        this.setResizable(false);
        conn = Connections.java_db();
        loadalldatatable01 ();
        loadalldatatable02 ();
        
        String access=(comb_custype.getSelectedItem().toString());
        if(access == "Student"){
            comb_class.enable(true);
            txt_greadclass.enable(true);
            txt_greadclass.setText("");

        }else{
            comb_class.enable(false);
            comb_class.setSelectedItem("Null");
            txt_greadclass.enable(false);
            txt_greadclass.setText("Null");
        }
        
    }
    
    public void loadalldatatable01 (){
        try{
            
            String sql="Select * from books_tb";            
            
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            dataofbooks.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }finally{
            try{
                
                rs.close();
                pst.close();
                
            }catch(Exception e){
                
            }
        }
    
    }
    public void loadalldatatable02 (){
        try{
            
            String sql="Select * from customers";            
            
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            dataofcustomers.setModel(DbUtils.resultSetToTableModel(rs));
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }finally{
            try{
                
                rs.close();
                pst.close();
                
            }catch(Exception e){
                
            }
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataofbooks = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dataofcustomers = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_Btitle = new javax.swing.JTextField();
        txt_author = new javax.swing.JTextField();
        txt_BPdate = new javax.swing.JTextField();
        txt_Bisbn = new javax.swing.JTextField();
        txt_Bid = new javax.swing.JTextField();
        txt_remarks = new javax.swing.JTextField();
        txt_source = new javax.swing.JTextField();
        txt_price = new javax.swing.JTextField();
        txt_pages = new javax.swing.JTextField();
        txt_day = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_TP_number = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_Caddress2 = new javax.swing.JTextField();
        txt_Caddress1 = new javax.swing.JTextField();
        txt_companyname = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_bookid = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        txt_greadclass = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        checkcusid = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txt_regdate = new javax.swing.JTextField();
        txt_nic = new javax.swing.JTextField();
        txt_mobail = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        comb_sex = new javax.swing.JComboBox();
        comb_custype = new javax.swing.JComboBox();
        comb_class = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Library Manegement System...");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jButton1.setText("Cancal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        dataofbooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(dataofbooks);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1221, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Book Store", jPanel5);

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        dataofcustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(dataofcustomers);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1221, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Customer Store", jPanel6);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Book Id :");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ISBN No :");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Book Title :");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Author :");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Publish Date :");

        txt_day.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_dayActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Adding Date :");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Pages :");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Price :");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Source :");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Remarks :");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Company Name :");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Address 1 :");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Address 2 :");

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Company Email :");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("CompanyTP No :");

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Book Id :");

        txt_bookid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_bookidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_bookidKeyReleased(evt);
            }
        });

        jButton2.setText("Update Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });

        jButton3.setText("Delete Data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(txt_bookid, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(jButton3)
                        .addGap(103, 103, 103)
                        .addComponent(jButton4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Bisbn, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_BPdate, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_author, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Btitle, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Bid, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_day, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_pages, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_remarks, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_source, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_companyname, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Caddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_TP_number, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Caddress2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton2, jButton3, jButton4});

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txt_BPdate, txt_Bid, txt_Bisbn, txt_Btitle, txt_Caddress1, txt_Caddress2, txt_TP_number, txt_author, txt_companyname, txt_day, txt_email, txt_pages, txt_price, txt_remarks, txt_source});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(txt_bookid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(txt_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(txt_pages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(txt_source, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(txt_remarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txt_Bid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txt_Bisbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(txt_Btitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(txt_author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(txt_BPdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txt_companyname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txt_Caddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txt_Caddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txt_TP_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(67, 67, 67))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton2, jButton3, jButton4});

        jTabbedPane1.addTab("Edit For Book Store", jPanel3);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jButton5.setText("Update Data");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton5KeyPressed(evt);
            }
        });

        jButton6.setText("Delete Data");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton6KeyPressed(evt);
            }
        });

        jButton7.setText("Clear");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jButton7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton7KeyPressed(evt);
            }
        });

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Customer Id :");

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Customer Name :");

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Address :");

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Gread Of Class :");

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Sex :");

        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Customer Id :");

        checkcusid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                checkcusidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                checkcusidKeyReleased(evt);
            }
        });

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Mobail No :");

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("NIC No :");

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Register Date :");

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Customer Type :");

        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Class :");

        comb_sex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        comb_custype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Student", "Teacher" }));
        comb_custype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb_custypeActionPerformed(evt);
            }
        });

        comb_class.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Null", "Student", "O/L Student", "A/L Student" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(jButton6)
                        .addGap(103, 103, 103)
                        .addComponent(jButton7))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(checkcusid, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel19))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_name, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                    .addComponent(txt_address, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                    .addComponent(txt_id, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                    .addComponent(comb_sex, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_mobail, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)))
                        .addGap(182, 182, 182)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel26))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_nic, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                            .addComponent(txt_regdate, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                            .addComponent(comb_custype, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(comb_class, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_greadclass, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txt_address, txt_greadclass, txt_id, txt_mobail, txt_name, txt_nic, txt_regdate});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton5, jButton6, jButton7});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel24)
                        .addComponent(checkcusid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(txt_nic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(txt_regdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(comb_custype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(comb_class, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(txt_greadclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(comb_sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txt_mobail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addGap(67, 67, 67))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton5, jButton6, jButton7});

        jTabbedPane1.addTab("Edit For Customer Store", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator3)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTabbedPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)))
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1280, 570));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Library Store...");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1280, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/StoreBG.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 669));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Library_Manegement_System_Administetor windowshow= new Library_Manegement_System_Administetor();
        windowshow.show();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_bookidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_bookidKeyReleased
           
        try{
            
            //books
            String a=txt_bookid.getText();
            String sql="select * from books_tb where book_id="+a+"";
            
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            
            while(rs.next()){
                txt_Bid.setText(rs.getString("book_id"));
                txt_Bisbn.setText(rs.getString("book_isbn_no"));
                txt_Btitle.setText(rs.getString("book_title"));
                txt_author.setText(rs.getString("book_author"));
                txt_BPdate.setText(rs.getString("publish_date"));
                txt_companyname.setText(rs.getString("company_name"));
                txt_Caddress1.setText(rs.getString("address1"));
                txt_Caddress2.setText(rs.getString("address2"));
                txt_email.setText(rs.getString("company_email"));
                txt_TP_number.setText(rs.getString("company_tp_no"));
                txt_day.setText(rs.getString("adding_date"));
                txt_pages.setText(rs.getString("pages"));
                txt_price.setText(rs.getString("price"));
                txt_source.setText(rs.getString("source"));
                txt_remarks.setText(rs.getString("remark"));
            }
        }catch(Exception e){
            
            
            
        }finally{
            try{
                
                rs.close();
                pst.close();
                
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_txt_bookidKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        txt_Bid.setText("");
        txt_Bisbn.setText("");
        txt_Btitle.setText("");
        txt_author.setText("");
        txt_BPdate.setText("");
        txt_day.setText("");
        txt_pages.setText("");
        txt_price.setText("");
        txt_source.setText("");
        txt_remarks.setText("");
           
        txt_companyname.setText("");
        txt_Caddress1.setText("");
        txt_Caddress2.setText("");
        txt_email.setText("");
        txt_TP_number.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void checkcusidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_checkcusidKeyReleased
        try{
            
            //books
            String aid=checkcusid.getText();
            String sql="select * from customers where customer_id="+aid+"";
            
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            
            while(rs.next()){
                txt_id.setText(rs.getString("customer_id"));
                txt_name.setText(rs.getString("customer_name"));
                txt_address.setText(rs.getString("address"));
                comb_sex.setSelectedItem(rs.getString("sex"));
                txt_mobail.setText(rs.getString("mobail_no"));
                txt_nic.setText(rs.getString("nic_no"));
                txt_regdate.setText(rs.getString("register_date"));
                comb_custype.setSelectedItem(rs.getString("customer_type"));
                comb_class.setSelectedItem(rs.getString("class"));
                txt_greadclass.setText(rs.getString("gread_of_class"));
            }
        }catch(Exception e){
            
            
            
        }finally{
            try{
                
                rs.close();
                pst.close();
                
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_checkcusidKeyReleased

    private void comb_custypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb_custypeActionPerformed
        String access=(comb_custype.getSelectedItem().toString());
        if(access == "Student"){
            comb_class.enable(true);
            txt_greadclass.enable(true);
            txt_greadclass.setText("");

        }else{
            comb_class.enable(false);
            comb_class.setSelectedItem("Null");
            txt_greadclass.enable(false);
            txt_greadclass.setText("Null");
        }
    }//GEN-LAST:event_comb_custypeActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Customers Update=============================
        int confirmed = JOptionPane.showConfirmDialog(null, 
        "Are you sure you want to update this customer?", "Update Program Message Box",
        JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
        int value0 = USER.UserId;
        String value1 = USER.UserName;
        String CcheckID=checkcusid.getText();
        String CID=txt_id.getText();
        String CNAME=txt_name.getText();
        String CADDRESS=txt_address.getText();
        String CSEX=(comb_sex.getSelectedItem().toString());
        String CMOBAIL=txt_mobail.getText();
        String CNICNO=txt_nic.getText();
        String Cregdate=txt_regdate.getText();
        String Ctype=(comb_custype.getSelectedItem().toString());
        String Cclass=(comb_class.getSelectedItem().toString());
        String Cgreadclass=txt_greadclass.getText();
        
        try{
            
            //Update=====
            
            String sql="UPDATE customers SET customer_id='"+CID+"',customer_name='"+CNAME+"',address='"+CADDRESS+"',"
                    +"sex='"+CSEX+"',mobail_no='"+CMOBAIL+"',nic_no='"+CNICNO+"',register_date='"+Cregdate+"',"
                    +"customer_type='"+Ctype+"',class='"+Cclass+"',gread_of_class='"+Cgreadclass+"' WHERE customer_id='"+CcheckID+"'";
            
            pst=conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(this, "Update Successfull...");
            loadalldatatable01 ();
        loadalldatatable02 ();
        
            try{
                Date currentDate = GregorianCalendar.getInstance().getTime();
                DateFormat df = DateFormat.getDateInstance();
                String datestring = df.format(currentDate);
                    
                Date d = new Date ();
                SimpleDateFormat sdf = new SimpleDateFormat ("hh:mm:ss");
                String timestring = sdf.format(d);
                    
                
                String value2 = timestring;
                String value3 = datestring;
        
                sql="Insert into audit_tb (User_Id,User_Name,Date,Status)"
                        +"values("+value0+",'"+value1+"','"+value3+" / "+value2+"','Customer Updated...')";
                pst=conn.prepareStatement(sql);
                pst.execute();
            
            }catch(Exception e){
            
                JOptionPane.showMessageDialog(null, e);
            
            }finally{
                try{
                
                    rs.close();
                    pst.close();
                
                }catch(Exception e){
                
                }
            }
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
            
        }finally{
            try{
                txt_bookid.setText("");
                
                rs.close();
                pst.close();
                
            }catch(Exception e){
                
            }
        }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // Customers Delete=============================
        int confirmed = JOptionPane.showConfirmDialog(null, 
        "Are you sure you want to delete this customer?", "Delete Program Message Box",
        JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
        int value0 = USER.UserId;
        String value1 = USER.UserName;
        String CcheckID=checkcusid.getText();
        
        try{
            
            //Delete=====
            
            String sql="DELETE FROM customers WHERE customer_id='"+CcheckID+"'";
            
            pst=conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(this, "Delete Successfull...");
            loadalldatatable01 ();
        loadalldatatable02 ();
        
            try{
                Date currentDate = GregorianCalendar.getInstance().getTime();
                DateFormat df = DateFormat.getDateInstance();
                String datestring = df.format(currentDate);
                    
                Date d = new Date ();
                SimpleDateFormat sdf = new SimpleDateFormat ("hh:mm:ss");
                String timestring = sdf.format(d);
                    
                
                String value2 = timestring;
                String value3 = datestring;
        
                sql="Insert into audit_tb (User_Id,User_Name,Date,Status)"
                        +"values("+value0+",'"+value1+"','"+value3+" / "+value2+"','Customer Deleted...')";
                pst=conn.prepareStatement(sql);
                pst.execute();
            
            }catch(Exception e){
            
                JOptionPane.showMessageDialog(null, e);
            
            }finally{
                try{
                
                    rs.close();
                    pst.close();
                
                }catch(Exception e){
                
                }
            }
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
            
        }finally{
            try{
                txt_bookid.setText("");
                
                rs.close();
                pst.close();
                
            }catch(Exception e){
                
            }
        }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Books Update====================Error=========
        int confirmed = JOptionPane.showConfirmDialog(null, 
        "Are you sure you want to update this book?", "Update Program Message Box",
        JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
        int value0 = USER.UserId;
        String value1 = USER.UserName;
        
        String BcheckID=txt_bookid.getText();
        
        String BID=txt_Bid.getText();
        String BISBN=txt_Bisbn.getText();
        String Btitle=txt_Btitle.getText();
        String BAuthor=txt_author.getText();
        String BPublishDate=txt_BPdate.getText();
        String BCompanyName=txt_companyname.getText();
        String CAddress1=txt_Caddress1.getText();
        String CAddress2=txt_Caddress2.getText();
        String BCompanyEmail=txt_email.getText();
        String BCompanyTpNo=txt_TP_number.getText();
        String BAddingDate=txt_day.getText();
        String BPages=txt_pages.getText();
        String BPrice=txt_price.getText();
        String BSource=txt_source.getText();
        String BRemark=txt_remarks.getText();
        
        try{
            
            //Update=====
            
            String sql="UPDATE books_tb SET book_id='"+BID+"',book_isbn_no='"+BISBN+"',book_title='"+Btitle+"',"
                    +"book_author='"+BAuthor+"',publish_date='"+BPublishDate+"',company_name='"+BCompanyName+"',address1='"+CAddress1+"',"
                    +"address2='"+CAddress2+"',company_email='"+BCompanyEmail+"',company_tp_no='"+BCompanyTpNo+"',adding_date='"+BAddingDate+"',"
                    +"pages='"+BPages+"',price='"+BPrice+"',source='"+BSource+"',remark='"+BRemark+"' WHERE book_id='"+BcheckID+"'";
            
            pst=conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(this, "Update Successfull...");
            loadalldatatable01 ();
            loadalldatatable02 ();
        
            try{
                Date currentDate = GregorianCalendar.getInstance().getTime();
                DateFormat df = DateFormat.getDateInstance();
                String datestring = df.format(currentDate);
                    
                Date d = new Date ();
                SimpleDateFormat sdf = new SimpleDateFormat ("hh:mm:ss");
                String timestring = sdf.format(d);
                    
                
                String value2 = timestring;
                String value3 = datestring;
        
                sql="Insert into audit_tb (User_Id,User_Name,Date,Status)"
                        +"values("+value0+",'"+value1+"','"+value3+" / "+value2+"','Book Updated...')";
                pst=conn.prepareStatement(sql);
                pst.execute();
            
            }catch(Exception e){
            
                JOptionPane.showMessageDialog(null, e);
            
            }finally{
                try{
                
                    rs.close();
                    pst.close();
                
                }catch(Exception e){
                
                }
            }
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
            
        }finally{
            try{
                txt_bookid.setText("");
                
                rs.close();
                pst.close();
                
            }catch(Exception e){
                
            }
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Books Delete=============================
        int confirmed = JOptionPane.showConfirmDialog(null, 
        "Are you sure you want to delete this book?", "Delete Program Message Box",
        JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
        int value0 = USER.UserId;
        String value1 = USER.UserName;
        String BcheckID=txt_bookid.getText();
        
        try{
            
            //Delete=====
            
            String sql="DELETE FROM books_tb WHERE book_id='"+BcheckID+"'";
            
            pst=conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(this, "Delete Successfull...");
            loadalldatatable01 ();
        loadalldatatable02 ();
        
            try{
                Date currentDate = GregorianCalendar.getInstance().getTime();
                DateFormat df = DateFormat.getDateInstance();
                String datestring = df.format(currentDate);
                    
                Date d = new Date ();
                SimpleDateFormat sdf = new SimpleDateFormat ("hh:mm:ss");
                String timestring = sdf.format(d);
                    
                
                String value2 = timestring;
                String value3 = datestring;
        
                sql="Insert into audit_tb (User_Id,User_Name,Date,Status)"
                        +"values("+value0+",'"+value1+"','"+value3+" / "+value2+"','Book Deleted...')";
                pst=conn.prepareStatement(sql);
                pst.execute();
            
            }catch(Exception e){
            
                JOptionPane.showMessageDialog(null, e);
            
            }finally{
                try{
                
                    rs.close();
                    pst.close();
                
                }catch(Exception e){
                
                }
            }
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
            
        }finally{
            try{
                txt_bookid.setText("");
                
                rs.close();
                pst.close();
                
            }catch(Exception e){
                
            }
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        checkcusid.setText("");
        txt_id.setText("");
        txt_name.setText("");
        txt_address.setText("");
        comb_sex.setSelectedItem("Male");
        txt_mobail.setText("");
        txt_nic.setText("");
        txt_regdate.setText("");
        comb_custype.setSelectedItem("Student");
        comb_class.setSelectedItem("Null");
        txt_greadclass.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void txt_dayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_dayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dayActionPerformed

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            Library_Manegement_System_Administetor windowshow= new Library_Manegement_System_Administetor();
        windowshow.show();
        this.dispose();
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            // Books Update====================Error=========
        int confirmed = JOptionPane.showConfirmDialog(null, 
        "Are you sure you want to update this book?", "Update Program Message Box",
        JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
        int value0 = USER.UserId;
        String value1 = USER.UserName;
        
        String BcheckID=txt_bookid.getText();
        
        String BID=txt_Bid.getText();
        String BISBN=txt_Bisbn.getText();
        String Btitle=txt_Btitle.getText();
        String BAuthor=txt_author.getText();
        String BPublishDate=txt_BPdate.getText();
        String BCompanyName=txt_companyname.getText();
        String CAddress1=txt_Caddress1.getText();
        String CAddress2=txt_Caddress2.getText();
        String BCompanyEmail=txt_email.getText();
        String BCompanyTpNo=txt_TP_number.getText();
        String BAddingDate=txt_day.getText();
        String BPages=txt_pages.getText();
        String BPrice=txt_price.getText();
        String BSource=txt_source.getText();
        String BRemark=txt_remarks.getText();
        
        try{
            
            //Update=====
            
            String sql="UPDATE books_tb SET book_id='"+BID+"',book_isbn_no='"+BISBN+"',book_title='"+Btitle+"',"
                    +"book_author='"+BAuthor+"',publish_date='"+BPublishDate+"',company_name='"+BCompanyName+"',address1='"+CAddress1+"',"
                    +"address2='"+CAddress2+"',company_email='"+BCompanyEmail+"',company_tp_no='"+BCompanyTpNo+"',adding_date='"+BAddingDate+"',"
                    +"pages='"+BPages+"',price='"+BPrice+"',source='"+BSource+"',remark='"+BRemark+"' WHERE book_id='"+BcheckID+"'";
            
            pst=conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(this, "Update Successfull...");
            loadalldatatable01 ();
        loadalldatatable02 ();
        
            try{
                Date currentDate = GregorianCalendar.getInstance().getTime();
                DateFormat df = DateFormat.getDateInstance();
                String datestring = df.format(currentDate);
                    
                Date d = new Date ();
                SimpleDateFormat sdf = new SimpleDateFormat ("hh:mm:ss");
                String timestring = sdf.format(d);
                    
                
                String value2 = timestring;
                String value3 = datestring;
        
                sql="Insert into audit_tb (User_Id,User_Name,Date,Status)"
                        +"values("+value0+",'"+value1+"','"+value3+" / "+value2+"','Book Updated...')";
                pst=conn.prepareStatement(sql);
                pst.execute();
            
            }catch(Exception e){
            
                JOptionPane.showMessageDialog(null, e);
            
            }finally{
                try{
                
                    rs.close();
                    pst.close();
                
                }catch(Exception e){
                
                }
            }
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
            
        }finally{
            try{
                txt_bookid.setText("");
                
                rs.close();
                pst.close();
                
            }catch(Exception e){
                
            }
        }
        }
        }
    }//GEN-LAST:event_jButton2KeyPressed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            // Books Delete=============================
        int confirmed = JOptionPane.showConfirmDialog(null, 
        "Are you sure you want to delete this book?", "Delete Program Message Box",
        JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
        int value0 = USER.UserId;
        String value1 = USER.UserName;
        String BcheckID=txt_bookid.getText();
        
        try{
            
            //Delete=====
            
            String sql="DELETE FROM books_tb WHERE book_id='"+BcheckID+"'";
            
            pst=conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(this, "Delete Successfull...");
            loadalldatatable01 ();
        loadalldatatable02 ();
        
            try{
                Date currentDate = GregorianCalendar.getInstance().getTime();
                DateFormat df = DateFormat.getDateInstance();
                String datestring = df.format(currentDate);
                    
                Date d = new Date ();
                SimpleDateFormat sdf = new SimpleDateFormat ("hh:mm:ss");
                String timestring = sdf.format(d);
                    
                
                String value2 = timestring;
                String value3 = datestring;
        
                sql="Insert into audit_tb (User_Id,User_Name,Date,Status)"
                        +"values("+value0+",'"+value1+"','"+value3+" / "+value2+"','Book Deleted...')";
                pst=conn.prepareStatement(sql);
                pst.execute();
            
            }catch(Exception e){
            
                JOptionPane.showMessageDialog(null, e);
            
            }finally{
                try{
                
                    rs.close();
                    pst.close();
                
                }catch(Exception e){
                
                }
            }
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
            
        }finally{
            try{
                txt_bookid.setText("");
                
                rs.close();
                pst.close();
                
            }catch(Exception e){
                
            }
        }
        }
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            txt_Bid.setText("");
        txt_Bisbn.setText("");
        txt_Btitle.setText("");
        txt_author.setText("");
        txt_BPdate.setText("");
        txt_day.setText("");
        txt_pages.setText("");
        txt_price.setText("");
        txt_source.setText("");
        txt_remarks.setText("");
           
        txt_companyname.setText("");
        txt_Caddress1.setText("");
        txt_Caddress2.setText("");
        txt_email.setText("");
        txt_TP_number.setText("");
        }
    }//GEN-LAST:event_jButton4KeyPressed

    private void jButton5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            // Customers Update=============================
        int confirmed = JOptionPane.showConfirmDialog(null, 
        "Are you sure you want to update this customer?", "Update Program Message Box",
        JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
        int value0 = USER.UserId;
        String value1 = USER.UserName;
        String CcheckID=checkcusid.getText();
        String CID=txt_id.getText();
        String CNAME=txt_name.getText();
        String CADDRESS=txt_address.getText();
        String CSEX=(comb_sex.getSelectedItem().toString());
        String CMOBAIL=txt_mobail.getText();
        String CNICNO=txt_nic.getText();
        String Cregdate=txt_regdate.getText();
        String Ctype=(comb_custype.getSelectedItem().toString());
        String Cclass=(comb_class.getSelectedItem().toString());
        String Cgreadclass=txt_greadclass.getText();
        
        try{
            
            //Update=====
            
            String sql="UPDATE customers SET customer_id='"+CID+"',customer_name='"+CNAME+"',address='"+CADDRESS+"',"
                    +"sex='"+CSEX+"',mobail_no='"+CMOBAIL+"',nic_no='"+CNICNO+"',register_date='"+Cregdate+"',"
                    +"customer_type='"+Ctype+"',class='"+Cclass+"',gread_of_class='"+Cgreadclass+"' WHERE customer_id='"+CcheckID+"'";
            
            pst=conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(this, "Update Successfull...");
            loadalldatatable01 ();
        loadalldatatable02 ();
        
            try{
                Date currentDate = GregorianCalendar.getInstance().getTime();
                DateFormat df = DateFormat.getDateInstance();
                String datestring = df.format(currentDate);
                    
                Date d = new Date ();
                SimpleDateFormat sdf = new SimpleDateFormat ("hh:mm:ss");
                String timestring = sdf.format(d);
                    
                
                String value2 = timestring;
                String value3 = datestring;
        
                sql="Insert into audit_tb (User_Id,User_Name,Date,Status)"
                        +"values("+value0+",'"+value1+"','"+value3+" / "+value2+"','Customer Updated...')";
                pst=conn.prepareStatement(sql);
                pst.execute();
            
            }catch(Exception e){
            
                JOptionPane.showMessageDialog(null, e);
            
            }finally{
                try{
                
                    rs.close();
                    pst.close();
                
                }catch(Exception e){
                
                }
            }
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
            
        }finally{
            try{
                txt_bookid.setText("");
                
                rs.close();
                pst.close();
                
            }catch(Exception e){
                
            }
        }
        }
        }
    }//GEN-LAST:event_jButton5KeyPressed

    private void jButton6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton6KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            // Customers Delete=============================
        int confirmed = JOptionPane.showConfirmDialog(null, 
        "Are you sure you want to delete this customer?", "Delete Program Message Box",
        JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
        int value0 = USER.UserId;
        String value1 = USER.UserName;
        String CcheckID=checkcusid.getText();
        
        try{
            
            //Delete=====
            
            String sql="DELETE FROM customers WHERE customer_id='"+CcheckID+"'";
            
            pst=conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(this, "Delete Successfull...");
            loadalldatatable01 ();
        loadalldatatable02 ();
        
            try{
                Date currentDate = GregorianCalendar.getInstance().getTime();
                DateFormat df = DateFormat.getDateInstance();
                String datestring = df.format(currentDate);
                    
                Date d = new Date ();
                SimpleDateFormat sdf = new SimpleDateFormat ("hh:mm:ss");
                String timestring = sdf.format(d);
                    
                
                String value2 = timestring;
                String value3 = datestring;
        
                sql="Insert into audit_tb (User_Id,User_Name,Date,Status)"
                        +"values("+value0+",'"+value1+"','"+value3+" / "+value2+"','Customer Deleted...')";
                pst=conn.prepareStatement(sql);
                pst.execute();
            
            }catch(Exception e){
            
                JOptionPane.showMessageDialog(null, e);
            
            }finally{
                try{
                
                    rs.close();
                    pst.close();
                
                }catch(Exception e){
                
                }
            }
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
            
        }finally{
            try{
                txt_bookid.setText("");
                
                rs.close();
                pst.close();
                
            }catch(Exception e){
                
            }
        }
        }
        }
    }//GEN-LAST:event_jButton6KeyPressed

    private void jButton7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton7KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            checkcusid.setText("");
        txt_id.setText("");
        txt_name.setText("");
        txt_address.setText("");
        comb_sex.setSelectedItem("Male");
        txt_mobail.setText("");
        txt_nic.setText("");
        txt_regdate.setText("");
        comb_custype.setSelectedItem("Student");
        comb_class.setSelectedItem("Null");
        txt_greadclass.setText("");
        }
    }//GEN-LAST:event_jButton7KeyPressed

    private void checkcusidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_checkcusidKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_BACK_SPACE){
        checkcusid.setText("");
        txt_id.setText("");
        txt_name.setText("");
        txt_address.setText("");
        comb_sex.setSelectedItem("Male");
        txt_mobail.setText("");
        txt_nic.setText("");
        txt_regdate.setText("");
        comb_custype.setSelectedItem("Student");
        comb_class.setSelectedItem("Null");
        txt_greadclass.setText("");
        }
    }//GEN-LAST:event_checkcusidKeyPressed

    private void txt_bookidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_bookidKeyPressed
        // book==========
        if (evt.getKeyCode()==KeyEvent.VK_BACK_SPACE){
            txt_Bid.setText("");
            txt_Bisbn.setText("");
            txt_Btitle.setText("");
            txt_author.setText("");
            txt_BPdate.setText("");
            txt_day.setText("");
            txt_pages.setText("");
            txt_price.setText("");
            txt_source.setText("");
            txt_remarks.setText("");
           
            txt_companyname.setText("");
            txt_Caddress1.setText("");
            txt_Caddress2.setText("");
            txt_email.setText("");
            txt_TP_number.setText("");
        }
    }//GEN-LAST:event_txt_bookidKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Library_Manegement_System_Strock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Library_Manegement_System_Strock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Library_Manegement_System_Strock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Library_Manegement_System_Strock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Library_Manegement_System_Strock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField checkcusid;
    private javax.swing.JComboBox comb_class;
    private javax.swing.JComboBox comb_custype;
    private javax.swing.JComboBox comb_sex;
    private javax.swing.JTable dataofbooks;
    private javax.swing.JTable dataofcustomers;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txt_BPdate;
    private javax.swing.JTextField txt_Bid;
    private javax.swing.JTextField txt_Bisbn;
    private javax.swing.JTextField txt_Btitle;
    private javax.swing.JTextField txt_Caddress1;
    private javax.swing.JTextField txt_Caddress2;
    private javax.swing.JTextField txt_TP_number;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_author;
    private javax.swing.JTextField txt_bookid;
    private javax.swing.JTextField txt_companyname;
    private javax.swing.JTextField txt_day;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_greadclass;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_mobail;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_nic;
    private javax.swing.JTextField txt_pages;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_regdate;
    private javax.swing.JTextField txt_remarks;
    private javax.swing.JTextField txt_source;
    // End of variables declaration//GEN-END:variables

    private ImageIcon format=null;
    String filename=null;
    byte[] person_image=null;
    
    private void seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("LibraryMS.png")));
    }
}
