/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LIBRARYMANAGEMENTSYSTEM0_1.Windows;

import LIBRARYMANAGEMENTSYSTEM0_1.Connection.Connections;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.HashSet;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.TableModel;

/**
 *
 * @author Anjana
 */
public class Library_Manegement_System_AdminNewCustomers extends javax.swing.JFrame {
Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;




    /**
     * Creates new form Library_Manegement_System_AdminNewCustomers
     */
    public Library_Manegement_System_AdminNewCustomers() {
        initComponents();
        currentdate();
        seticon();
        this.setResizable(false);
        lab_userid.setText(String.valueOf(USER.UserId).toString());
        lab_username.setText(String.valueOf(USER.UserName).toString());//lab_username
        
        getlastdata();
        
    }
    
    /*get last data*/
    public void getlastdata(){
        conn = Connections.java_db();
        try{
            String sql="SELECT * FROM customers ORDER BY customer_id DESC LIMIT 1";
            
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                String idbooks=Integer.toString(1+(rs.getInt("customer_id")));
                txt_id.setText(idbooks);
            }
        }catch(Exception e){
            
        }
    } 

    
    public void currentdate(){
        Calendar cal=new GregorianCalendar();
        int month=cal.get(Calendar.MONTH);
        int year=cal.get(Calendar.YEAR);
        int day=cal.get(Calendar.DAY_OF_MONTH);
        
        //txt_regdate.setText((month+1)+"/"+(day)+"/"+(year));
        txt_regdate.setText((year)+"/"+(month+1)+"/"+(day));
    }
    
       
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_mobail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_regdate = new javax.swing.JTextField();
        txt_nic = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comb_custype = new javax.swing.JComboBox();
        ClassPanel = new javax.swing.JPanel();
        comb_class = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_greadclass = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        comb_sex = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        lab_userid = new javax.swing.JLabel();
        lab_username = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Library Manegement System...");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer Id :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 198, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer Name :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));
        jPanel1.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 198, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Address :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));
        jPanel1.add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 198, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NIC No :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mobail No :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        txt_mobail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mobailActionPerformed(evt);
            }
        });
        jPanel1.add(txt_mobail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 198, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Register Date :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));
        jPanel1.add(txt_regdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 198, -1));
        jPanel1.add(txt_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 198, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Customer Type :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));

        comb_custype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Student", "Teacher" }));
        comb_custype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comb_custypeActionPerformed(evt);
            }
        });
        jPanel1.add(comb_custype, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 200, -1));

        ClassPanel.setBackground(new java.awt.Color(51, 51, 51));
        ClassPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        comb_class.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Null", "Student", "O/L Student", "A/L Student" }));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Class :");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Gread Of Class :");

        javax.swing.GroupLayout ClassPanelLayout = new javax.swing.GroupLayout(ClassPanel);
        ClassPanel.setLayout(ClassPanelLayout);
        ClassPanelLayout.setHorizontalGroup(
            ClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClassPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ClassPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(comb_class, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ClassPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txt_greadclass)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        ClassPanelLayout.setVerticalGroup(
            ClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClassPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClassPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8))
                    .addComponent(comb_class, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ClassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_greadclass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(ClassPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 71, -1));

        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 71, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Sex :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, -1, -1));

        comb_sex.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        jPanel1.add(comb_sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 200, -1));

        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 67, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 670, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 670, 10));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Library Manegement System 0.1");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 710, 360));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Add New Customer...");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Logged in as :");

        lab_userid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lab_userid.setForeground(new java.awt.Color(255, 255, 255));
        lab_userid.setText("userid");

        lab_username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lab_username.setForeground(new java.awt.Color(255, 255, 255));
        lab_username.setText("username");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User.png"))); // NOI18N
        jLabel16.setText("jLabel16");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(10, 10, 10)
                                .addComponent(lab_userid))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(lab_username)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lab_userid)
                                    .addComponent(jLabel15))
                                .addGap(3, 3, 3)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lab_username)
                                    .addComponent(jLabel13)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 710, 80));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BG.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_mobailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mobailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mobailActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Library_Manegement_System_Administetor windowshow= new Library_Manegement_System_Administetor();
        windowshow.show();
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void comb_custypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comb_custypeActionPerformed
        String access=(comb_custype.getSelectedItem().toString());
        if(access == "Student"){
            comb_class.enable(true);
            txt_greadclass.enable(true);
            txt_greadclass.setText("");

        }else{
            comb_class.enable(false);
            comb_class.setSelectedItem("Null");
            txt_greadclass.enable(false);
            txt_greadclass.setText("Null");
        }
        
    }//GEN-LAST:event_comb_custypeActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        getlastdata();
        txt_name.setText("");
        txt_address.setText("");
        txt_mobail.setText("");
        txt_nic.setText("");
        txt_greadclass.setText("");
        
             
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
           String id=txt_id.getText();
           String name=txt_name.getText();
           String address=txt_address.getText();
           String sex=(comb_sex.getSelectedItem().toString());
           String mobail=txt_mobail.getText();
           String nic=txt_nic.getText();
           String regdate=txt_regdate.getText();
           String custype=(comb_custype.getSelectedItem().toString());
           String sclass=(comb_class.getSelectedItem().toString());
           String greadclass=txt_greadclass.getText();
        
        try{
            
            conn = Connections.java_db();
            /*Statement stmt=conn.createStatement();
           
            String sql="insert into customers (customer_id,customer_name,address,sex,mobail_no,nic_no,"
                    +"register_date,customer_type,class,gread_of_class,image)"
                    +"values("+id+",'"+name+"','"+address+"','"+sex+"','"+mobail+"',"
                    +"'"+nic+"','"+regdate+"','"+custype+"','"+sclass+"','"+greadclass+"','"+person_image+"')";
            
            stmt.execute(sql);*/
            String sql="insert into customers (customer_id,customer_name,address,sex,mobail_no,nic_no,"
                    +"register_date,customer_type,class,gread_of_class)"
                    +"values(?,?,?,?,?,?,?,?,?,?)";
            pst=conn.prepareStatement(sql);
            pst.setString(1, id);
            pst.setString(2, name);
            pst.setString(3, address);
            pst.setString(4, sex);
            pst.setString(5, mobail);
            pst.setString(6, nic);
            pst.setString(7, regdate);
            pst.setString(8, custype);
            pst.setString(9, sclass);
            pst.setString(10, greadclass);
            
            pst.execute();
            
            getlastdata();
            JOptionPane.showMessageDialog(this, "Saved Successfull...");
            
            try{
            Date currentDate = GregorianCalendar.getInstance().getTime();
            DateFormat df = DateFormat.getDateInstance();
            String datestring = df.format(currentDate);
                    
            Date d = new Date ();
            SimpleDateFormat sdf = new SimpleDateFormat ("hh:mm:ss");
            String timestring = sdf.format(d);
                    
            int value0 = USER.UserId;
            String value1 = USER.UserName;
            String value2 = timestring;
            String value3 = datestring;
        
            sql="Insert into audit_tb (User_Id,User_Name,Date,Status)"
                    +"values("+value0+",'"+value1+"','"+value3+" / "+value2+"','Add New Customer...')";
            pst=conn.prepareStatement(sql);
            pst.execute();
            
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
            
        }finally{
            try{
                
                rs.close();
                pst.close();
                
            }catch(Exception e){
                
            }
        }
            
            
            txt_name.setText("");
            txt_address.setText("");
            txt_mobail.setText("");
            txt_nic.setText("");
            txt_greadclass.setText("");
            comb_class.setSelectedItem("Student");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
        int confirmed = JOptionPane.showConfirmDialog(null, 
        "Are you sure you want to clear this data?", "Clear Program Message Box",
        JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            getlastdata();
            txt_name.setText("");
            txt_address.setText("");
            txt_mobail.setText("");
            txt_nic.setText("");
            txt_greadclass.setText("");
        }
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
           String id=txt_id.getText();
           String name=txt_name.getText();
           String address=txt_address.getText();
           String sex=(comb_sex.getSelectedItem().toString());
           String mobail=txt_mobail.getText();
           String nic=txt_nic.getText();
           String regdate=txt_regdate.getText();
           String custype=(comb_custype.getSelectedItem().toString());
           String sclass=(comb_class.getSelectedItem().toString());
           String greadclass=txt_greadclass.getText();
        
        try{
            
            conn = Connections.java_db();
            Statement stmt=conn.createStatement();
           
            String sql="insert into customers (customer_id,customer_name,address,sex,mobail_no,nic_no,"
                    +"register_date,customer_type,class,gread_of_class)"
                    +"values("+id+",'"+name+"','"+address+"','"+sex+"','"+mobail+"',"
                    +"'"+nic+"','"+regdate+"','"+custype+"','"+sclass+"','"+greadclass+"')";
            
            stmt.execute(sql);
            
            
            /*sql="insert into customers (image)"
                    +"values('?')";
            
            pst.setBytes(1, person_image);
            pst.execute();*/
            getlastdata();
            JOptionPane.showMessageDialog(this, "Saved Successfull...");
            
            
            try{
            Date currentDate = GregorianCalendar.getInstance().getTime();
            DateFormat df = DateFormat.getDateInstance();
            String datestring = df.format(currentDate);
                    
            Date d = new Date ();
            SimpleDateFormat sdf = new SimpleDateFormat ("hh:mm:ss");
            String timestring = sdf.format(d);
                    
            int value0 = USER.UserId;
            String value1 = USER.UserName;
            String value2 = timestring;
            String value3 = datestring;
        
            sql="Insert into audit_tb (User_Id,User_Name,Date,Status)"
                    +"values("+value0+",'"+value1+"','"+value3+" / "+value2+"','Add New Customer...')";
            pst=conn.prepareStatement(sql);
            pst.execute();
            
        }catch(Exception e){
            
            JOptionPane.showMessageDialog(null, e);
            
        }finally{
            try{
                
                rs.close();
                pst.close();
                
            }catch(Exception e){
                
            }
        }
            
            
            txt_name.setText("");
            txt_address.setText("");
            txt_mobail.setText("");
            txt_nic.setText("");
            txt_greadclass.setText("");
            comb_class.setSelectedItem("Student");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        }  
    }//GEN-LAST:event_jButton2KeyPressed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
        Library_Manegement_System_Administetor windowshow= new Library_Manegement_System_Administetor();
        windowshow.show();
        this.dispose();
        }
    }//GEN-LAST:event_jButton4KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Library_Manegement_System_AdminNewCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Library_Manegement_System_AdminNewCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Library_Manegement_System_AdminNewCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Library_Manegement_System_AdminNewCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Library_Manegement_System_AdminNewCustomers().setVisible(true);
            }
        });
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ClassPanel;
    private javax.swing.JComboBox comb_class;
    private javax.swing.JComboBox comb_custype;
    private javax.swing.JComboBox comb_sex;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lab_userid;
    private javax.swing.JLabel lab_username;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_greadclass;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_mobail;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_nic;
    private javax.swing.JTextField txt_regdate;
    // End of variables declaration//GEN-END:variables
    
    private ImageIcon format=null;
    String filename=null;
    byte[] person_image=null;
    
    private void seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("LibraryMS.png")));
    }

}
