/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LIBRARYMANAGEMENTSYSTEM0_1.Windows;

import LIBRARYMANAGEMENTSYSTEM0_1.Connection.Connections;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Anjana
 */
public class Library_Manegement_System_AdminNewBooks extends javax.swing.JFrame {

    
    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    /**
     * Creates new form Library_Manegement_System_AdminNewBooks
     */
    public Library_Manegement_System_AdminNewBooks() {
        initComponents();
        currentdate();
        seticon();
        this.setResizable(false);
        conn = Connections.java_db();
        lab_userid.setText(String.valueOf(USER.UserId).toString());
        lab_username.setText(String.valueOf(USER.UserName).toString());//lab_username
        
        getlastdata();
        
    }
    
    /*get last data*/
    public void getlastdata(){
        conn = Connections.java_db();
        try{
            String sql="SELECT * FROM books_tb ORDER BY book_id DESC LIMIT 1";
            
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                String idbooks=Integer.toString(1+(rs.getInt("book_id")));
                txt_Bid.setText(idbooks);
            }
        }catch(Exception e){
            
        }
    }

    public void currentdate(){
        Calendar cal=new GregorianCalendar();
        int month=cal.get(Calendar.MONTH);
        int year=cal.get(Calendar.YEAR);
        int day=cal.get(Calendar.DAY_OF_MONTH);
        
        //txt_regdate.setText((month+1)+"/"+(day)+"/"+(year));
        txt_day.setText((year)+"/"+(month+1)+"/"+(day));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lab_userid = new javax.swing.JLabel();
        lab_username = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Button_Save = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txt_BPdate = new javax.swing.JTextField();
        txt_author = new javax.swing.JTextField();
        txt_Btitle = new javax.swing.JTextField();
        txt_Bisbn = new javax.swing.JTextField();
        txt_Bid = new javax.swing.JTextField();
        txt_day = new javax.swing.JTextField();
        txt_pages = new javax.swing.JTextField();
        txt_price = new javax.swing.JTextField();
        txt_source = new javax.swing.JTextField();
        txt_remarks = new javax.swing.JTextField();
        txt_companyname = new javax.swing.JTextField();
        txt_Caddress1 = new javax.swing.JTextField();
        txt_Caddress2 = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_TP_number = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Library Manegement System...");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Add New Books...");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Logged in as :");

        lab_userid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lab_userid.setForeground(new java.awt.Color(255, 255, 255));
        lab_userid.setText("userid");

        lab_username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lab_username.setForeground(new java.awt.Color(255, 255, 255));
        lab_username.setText("username");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator2)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jSeparator1)
                                .addContainerGap())
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lab_userid)
                                    .addComponent(lab_username))
                                .addGap(55, 55, 55))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(lab_userid))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lab_username)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 710, 90));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Button_Save.setText("Save");
        Button_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SaveActionPerformed(evt);
            }
        });
        Button_Save.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Button_SaveKeyPressed(evt);
            }
        });
        jPanel2.add(Button_Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 436, 65, -1));

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 436, 65, -1));

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 436, -1, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 427, 10));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Book Id :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ISBN No :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Book Title :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Author :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Publish Date :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Adding Date :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Pages :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Price :");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Source :");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Remarks :");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Place Of Publish :");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Company Name :");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Address 1 :");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Address 2 :");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Company Email :");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("CompanyTP No :");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));
        jPanel2.add(txt_BPdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 186, -1));
        jPanel2.add(txt_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 186, -1));
        jPanel2.add(txt_Btitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 186, -1));
        jPanel2.add(txt_Bisbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 186, -1));
        jPanel2.add(txt_Bid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 186, -1));
        jPanel2.add(txt_day, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 188, -1));
        jPanel2.add(txt_pages, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 188, -1));
        jPanel2.add(txt_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 188, -1));
        jPanel2.add(txt_source, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 188, -1));
        jPanel2.add(txt_remarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 188, -1));
        jPanel2.add(txt_companyname, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 426, -1));
        jPanel2.add(txt_Caddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 426, -1));

        txt_Caddress2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Caddress2ActionPerformed(evt);
            }
        });
        jPanel2.add(txt_Caddress2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 426, -1));
        jPanel2.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 426, -1));

        txt_TP_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TP_numberActionPerformed(evt);
            }
        });
        jPanel2.add(txt_TP_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 426, -1));

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Library Manegement System...");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 690, 10));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 470, 10));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 710, 480));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BG.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_Caddress2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Caddress2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Caddress2ActionPerformed

    private void txt_TP_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TP_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TP_numberActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Library_Manegement_System_Administetor windowshow= new Library_Manegement_System_Administetor();
        windowshow.show();
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
           getlastdata();
            txt_Bisbn.setText("");
            txt_Btitle.setText("");
            txt_author.setText("");
            txt_BPdate.setText("");
            txt_Caddress1.setText("");
            txt_Caddress2.setText("");
            txt_companyname.setText("");
            txt_TP_number.setText("");
            txt_email.setText("");
            txt_pages.setText("");
            txt_price.setText("");
            txt_source.setText("");
            txt_remarks.setText(""); 
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Button_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SaveActionPerformed
           String bid=txt_Bid.getText();
           String bisbn=txt_Bisbn.getText();
           String btitle=txt_Btitle.getText();
           String author=txt_author.getText();
           String BPdate=txt_BPdate.getText();
           String ADDday=txt_day.getText();
           String Bpages=txt_pages.getText();
           String Bprice=txt_price.getText();
           String Bsource=txt_source.getText();
           String Bremarks=txt_remarks.getText();
           
           String Comname=txt_companyname.getText();
           String Address1=txt_Caddress1.getText();
           String Address2=txt_Caddress2.getText();
           String Comemail=txt_email.getText();
           String ComTPno=txt_TP_number.getText();
           
           
        
        try{
            
            String sql="insert into books_tb (book_id,book_isbn_no,book_title,book_author,publish_date,company_name,address1,address2,company_email,company_tp_no,adding_date,pages,price,source,remark,In_Store)"
                    +"values("+bid+",'"+bisbn+"','"+btitle+"','"+author+"','"+BPdate+"','"+Comname+"','"+Address1+"','"+Address2+"','"+Comemail+"','"+ComTPno+"','"+ADDday+"','"+Bpages+"',"+Bprice+",'"+Bsource+"','"+Bremarks+"','Yes')";
            
            pst=conn.prepareStatement(sql);
            pst.execute();
            getlastdata();
            JOptionPane.showMessageDialog(this, "Saved Successfull...");
            
            try{
                Date currentDate = GregorianCalendar.getInstance().getTime();
                DateFormat df = DateFormat.getDateInstance();
                String datestring = df.format(currentDate);
                    
                Date d = new Date ();
                SimpleDateFormat sdf = new SimpleDateFormat ("hh:mm:ss");
                String timestring = sdf.format(d);
                    
                int value0 = USER.UserId;
                String value1 = USER.UserName;
                String value2 = timestring;
                String value3 = datestring;
        
                sql="Insert into audit_tb (User_Id,User_Name,Date,Status)"
                        +"values("+value0+",'"+value1+"','"+value3+" / "+value2+"','Add New Book...')";
                pst=conn.prepareStatement(sql);
                pst.execute();
            
            }catch(Exception e){
            
                JOptionPane.showMessageDialog(null, e);
            
            }finally{
                try{
                
                    rs.close();
                    pst.close();
                
                }catch(Exception e){
                
                }
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Thamidu"+e);
        }
        finally{
                try{
                    
                    txt_Bisbn.setText("");
                    txt_Btitle.setText("");
                    txt_author.setText("");
                    txt_BPdate.setText("");
                    txt_Caddress1.setText("");
                    txt_Caddress2.setText("");
                    txt_companyname.setText("");
                    txt_TP_number.setText("");
                    txt_email.setText("");
                    txt_pages.setText("");
                    txt_price.setText("");
                    txt_source.setText("");
                    txt_remarks.setText("");
                
                    rs.close();
                    pst.close();
                
                }catch(Exception e){
                
                }
            }
    }//GEN-LAST:event_Button_SaveActionPerformed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
        Library_Manegement_System_Administetor windowshow= new Library_Manegement_System_Administetor();
        windowshow.show();
        this.dispose();
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
        int confirmed = JOptionPane.showConfirmDialog(null, 
        "Are you sure you want to clear this data?", "Clear Program Message Box",
        JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            try{
                getlastdata();
                txt_Bisbn.setText("");
                txt_Btitle.setText("");
                txt_author.setText("");
                txt_BPdate.setText("");
                txt_Caddress1.setText("");
                txt_Caddress2.setText("");
                txt_companyname.setText("");
                txt_TP_number.setText("");
                txt_email.setText("");
                txt_pages.setText("");
                txt_price.setText("");
                txt_source.setText("");
                txt_remarks.setText(""); 
            }catch(Exception e){
            
            }
        }
        }
    }//GEN-LAST:event_jButton2KeyPressed

    private void Button_SaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Button_SaveKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){  
            String bid=txt_Bid.getText();
           String bisbn=txt_Bisbn.getText();
           String btitle=txt_Btitle.getText();
           String author=txt_author.getText();
           String BPdate=txt_BPdate.getText();
           String ADDday=txt_day.getText();
           String Bpages=txt_pages.getText();
           String Bprice=txt_price.getText();
           String Bsource=txt_source.getText();
           String Bremarks=txt_remarks.getText();
           
           String Comname=txt_companyname.getText();
           String Address1=txt_Caddress1.getText();
           String Address2=txt_Caddress2.getText();
           String Comemail=txt_email.getText();
           String ComTPno=txt_TP_number.getText();
           
           
        
        try{
            
            String sql="insert into books_tb (book_id,book_isbn_no,book_title,book_author,publish_date,company_name,address1,address2,company_email,company_tp_no,adding_date,pages,price,source,remark,In_Store)"
                    +"values("+bid+",'"+bisbn+"','"+btitle+"','"+author+"','"+BPdate+"','"+Comname+"','"+Address1+"','"+Address2+"','"+Comemail+"','"+ComTPno+"','"+ADDday+"','"+Bpages+"',"+Bprice+",'"+Bsource+"','"+Bremarks+"','Yes')";
            
            pst=conn.prepareStatement(sql);
            pst.execute();
            getlastdata();
            JOptionPane.showMessageDialog(this, "Saved Successfull...");
            
            try{
                Date currentDate = GregorianCalendar.getInstance().getTime();
                DateFormat df = DateFormat.getDateInstance();
                String datestring = df.format(currentDate);
                    
                Date d = new Date ();
                SimpleDateFormat sdf = new SimpleDateFormat ("hh:mm:ss");
                String timestring = sdf.format(d);
                    
                int value0 = USER.UserId;
                String value1 = USER.UserName;
                String value2 = timestring;
                String value3 = datestring;
        
                sql="Insert into audit_tb (User_Id,User_Name,Date,Status)"
                        +"values("+value0+",'"+value1+"','"+value3+" / "+value2+"','Add New Book...')";
                pst=conn.prepareStatement(sql);
                pst.execute();
            
            }catch(Exception e){
            
                JOptionPane.showMessageDialog(null, e);
            
            }finally{
                try{
                
                    rs.close();
                    pst.close();
                
                }catch(Exception e){
                
                }
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Thamidu"+e);
        }
        finally{
                try{
                    
                    txt_Bisbn.setText("");
                    txt_Btitle.setText("");
                    txt_author.setText("");
                    txt_BPdate.setText("");
                    txt_Caddress1.setText("");
                    txt_Caddress2.setText("");
                    txt_companyname.setText("");
                    txt_TP_number.setText("");
                    txt_email.setText("");
                    txt_pages.setText("");
                    txt_price.setText("");
                    txt_source.setText("");
                    txt_remarks.setText("");
                
                    rs.close();
                    pst.close();
                
                }catch(Exception e){
                
                }
            }
        }
    }//GEN-LAST:event_Button_SaveKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Library_Manegement_System_AdminNewBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Library_Manegement_System_AdminNewBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Library_Manegement_System_AdminNewBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Library_Manegement_System_AdminNewBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Library_Manegement_System_AdminNewBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Save;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lab_userid;
    private javax.swing.JLabel lab_username;
    private javax.swing.JTextField txt_BPdate;
    private javax.swing.JTextField txt_Bid;
    private javax.swing.JTextField txt_Bisbn;
    private javax.swing.JTextField txt_Btitle;
    private javax.swing.JTextField txt_Caddress1;
    private javax.swing.JTextField txt_Caddress2;
    private javax.swing.JTextField txt_TP_number;
    private javax.swing.JTextField txt_author;
    private javax.swing.JTextField txt_companyname;
    private javax.swing.JTextField txt_day;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_pages;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_remarks;
    private javax.swing.JTextField txt_source;
    // End of variables declaration//GEN-END:variables
private void seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("LibraryMS.png")));
    }
}
