/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LIBRARYMANAGEMENTSYSTEM0_1.Windows;

import LIBRARYMANAGEMENTSYSTEM0_1.Connection.Connections;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Anjana
 */
public class Library_Manegement_System_Setting extends javax.swing.JFrame {

    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form Library_Manegement_System_Setting
     */
    public Library_Manegement_System_Setting() {
        initComponents();
        conn = Connections.java_db();
        //lb_check.setVisible(false);
        themeapp();
        seticon();
        this.setResizable(false);
        lab_userid.setText(String.valueOf(USER.UserId).toString());
        lab_username.setText(String.valueOf(USER.UserName).toString());//lab_username
    }
    
    public void themeapp(){
        try{
            
            
            String sql="Select * from applicationtheme";
            
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            
            while(rs.next()){
                System.out.println("Have");
                String themename=rs.getString("Theme_Name");
                
                switch (themename){
                    case "Normal":
                        Themecombobox.setSelectedIndex(0);
                        System.out.println("Normal");
                        break;
                    case "AcrylLookAndFeel":
                        Themecombobox.setSelectedIndex(1);
                        System.out.println("AcrylLookAndFeel");
                        break;
                    case "AeroLookAndFeel":
                        Themecombobox.setSelectedIndex(2);
                        System.out.println("AeroLookAndFeel");
                        break;
                    case "AluminiumLookAndFeel":
                        Themecombobox.setSelectedIndex(3);
                        System.out.println("AluminiumLookAndFeel");
                        break;
                    case "BernsteinLookAndFeel":
                        Themecombobox.setSelectedIndex(4);
                        System.out.println("BernsteinLookAndFeel");
                        break;
                    case "FastLookAndFeel":
                        Themecombobox.setSelectedIndex(5);
                        System.out.println("FastLookAndFeel");
                        break;
                    case "HiFiLookAndFeel":
                        Themecombobox.setSelectedIndex(6);
                        System.out.println("HiFiLookAndFeel");
                        break;
                    case "McWinLookAndFeel":
                        Themecombobox.setSelectedIndex(7);
                        System.out.println("McWinLookAndFeel");
                        break;
                    case "MintLookAndFeel":
                        Themecombobox.setSelectedIndex(8);
                        System.out.println("MintLookAndFeel");
                        break;
                    case "NoireLookAndFeel":
                        Themecombobox.setSelectedIndex(9);
                        System.out.println("NoireLookAndFeel");
                        break;
                    case "SmartLookAndFeel":
                        Themecombobox.setSelectedIndex(10);
                        System.out.println("SmartLookAndFeel");
                        break;
                    case "LunaLookAndFeel":
                        Themecombobox.setSelectedIndex(11);
                        System.out.println("LunaLookAndFeel");
                        break;
                    case "TextureLookAndFeel":
                        Themecombobox.setSelectedIndex(12);
                        System.out.println("TextureLookAndFeel");
                        break;
                }
            }
        }catch(Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ucpass = new javax.swing.JPasswordField();
        upass = new javax.swing.JPasswordField();
        uname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        newcompass = new javax.swing.JPasswordField();
        newpass = new javax.swing.JPasswordField();
        username = new javax.swing.JTextField();
        usersid = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        img01 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        UserNamedrop = new javax.swing.JTextField();
        UserIddrop = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        Themecombobox = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        lab_userid = new javax.swing.JLabel();
        lab_username = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Library Manegement System...");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("Cancal");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jButton3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton3KeyPressed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 410, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 270, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 740, 10));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/download (3).jpg"))); // NOI18N
        jLabel14.setText("jLabel14");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 250, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 738, 10));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Library Manegement System...");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel9.setForeground(new java.awt.Color(0, 51, 204));
        jLabel9.setText("Library Manegement System...");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("It keeps a track of books issued, returned and added to the library.\n");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("It helps to provide information on any book present in library to the User who uses it.  ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Allows users to virtually Browse the books without doing so manually. ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User.png"))); // NOI18N
        jLabel16.setText("jLabel16");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 330, 52, 54));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User Name :");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password :");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Comform Password :");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton2KeyPressed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Please don't create anther account...!");

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/light2.png"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel20MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel20MouseReleased(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/light2.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel21MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel21MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(uname)
                            .addComponent(upass)
                            .addComponent(ucpass, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButton1)
                        .addGap(67, 67, 67)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(upass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(ucpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2});

        jTabbedPane2.addTab("Create New Account", jPanel3);

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("User id :");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("User Name :");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("New Password :");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Comform Password :");

        usersid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                usersidKeyReleased(evt);
            }
        });

        jButton4.setText("Change");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jButton4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton4KeyPressed(evt);
            }
        });

        jButton5.setText("Clear");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton5KeyPressed(evt);
            }
        });

        img01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/light2.png"))); // NOI18N
        img01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                img01MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                img01MouseReleased(evt);
            }
        });

        img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/light2.png"))); // NOI18N
        img2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                img2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                img2MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel15)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newcompass, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                            .addComponent(newpass)
                            .addComponent(username)
                            .addComponent(usersid))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(img01)
                            .addComponent(img2)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jButton4)
                        .addGap(87, 87, 87)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton4, jButton5});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(usersid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(newpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(img01, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(newcompass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(img2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton4, jButton5});

        jTabbedPane2.addTab("Change Password", jPanel4);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("User id :");

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("User Name :");

        UserIddrop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                UserIddropKeyReleased(evt);
            }
        });

        jButton6.setText("Drop");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jButton6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton6KeyPressed(evt);
            }
        });

        jButton7.setText("Clear");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jButton7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton7KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserIddrop, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserNamedrop, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton6, jButton7});

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {UserIddrop, UserNamedrop});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(UserIddrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(UserNamedrop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton6, jButton7});

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {UserIddrop, UserNamedrop});

        jTabbedPane2.addTab("Drop Users", jPanel5);

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jButton8.setText("Save");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        Themecombobox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Themecombobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Normal", "AcrylLookAndFeel  ", "AeroLookAndFeel  ", "AluminiumLookAndFeel  ", "BernsteinLookAndFeel  ", "FastLookAndFeel  ", "HiFiLookAndFeel ", "McWinLookAndFeel  ", "MintLookAndFeel  ", "NoireLookAndFeel ", "SmartLookAndFeel ", "LunaLookAndFeel  ", "TextureLookAndFeel " }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(Themecombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Themecombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        jTabbedPane2.addTab("Theme", jPanel6);

        jPanel1.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 450, 260));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 760, 450));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Logged in as :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, -1, -1));

        lab_userid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lab_userid.setForeground(new java.awt.Color(255, 255, 255));
        lab_userid.setText("userid");
        getContentPane().add(lab_userid, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, -1));

        lab_username.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lab_username.setForeground(new java.awt.Color(255, 255, 255));
        lab_username.setText("username");
        getContentPane().add(lab_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login01.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        Library_Manegement_System_Administetor windowshow= new Library_Manegement_System_Administetor();
        windowshow.show();
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        uname.setText("");
        upass.setText("");
        ucpass.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int value0 = USER.UserId;
        String value1 = USER.UserName;
        String UserName=uname.getText();
        String FPassword=upass.getText();
        String ComPassword=ucpass.getText();
        
        //if(FPassword == ComPassword){
        try{
            String sql="insert into users (USERNAME,PASSWORD)"
                    +"values('"+UserName+"',(sha1('"+ComPassword+"')))";
            
            pst=conn.prepareStatement(sql);
            pst.execute();
                        
            JOptionPane.showMessageDialog(this, "Saved Successfull...");
            
            
        
            try{
                Date currentDate = GregorianCalendar.getInstance().getTime();
                DateFormat df = DateFormat.getDateInstance();
                String datestring = df.format(currentDate);
                    
                Date d = new Date ();
                SimpleDateFormat sdf = new SimpleDateFormat ("hh:mm:ss");
                String timestring = sdf.format(d);
                    
                
                String value2 = timestring;
                String value3 = datestring;
                
        
                sql="Insert into audit_tb (User_Id,User_Name,Date,Status)"
                        +"values("+value0+",'"+UserName+"','"+value3+" / "+value2+"','Create New Account...')";
                pst=conn.prepareStatement(sql);
                pst.execute();
            
            }catch(Exception e){
            
                //JOptionPane.showMessageDialog(null, e);
            
            }finally{
                try{
                
                    rs.close();
                    pst.close();
                
                }catch(Exception e){
                    //JOptionPane.showMessageDialog(null, e);
                }
            }
            
        }catch(Exception e){
            
            //JOptionPane.showMessageDialog(null, e);
            
        }finally{
            try{
                uname.setText("");
                upass.setText("");
                ucpass.setText("");
                
                rs.close();
                pst.close();
                
            }catch(Exception e){
                //JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void usersidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usersidKeyReleased
        try{
            
            //users
            String a=usersid.getText();
            String sql="select USERNAME from users where ID="+a+"";
            
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            
            while(rs.next()){
                username.setText(rs.getString("USERNAME"));
            }
            
            
            
        }catch(Exception e){
            
            
            
        }finally{
            try{
                
                rs.close();
                pst.close();
                
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_usersidKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int confirmed = JOptionPane.showConfirmDialog(null, 
        "Are you sure you want to change the password?", "Change Password Program Message Box",
        JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
        int value0 = USER.UserId;
        String value1 = USER.UserName;
        String UserId=usersid.getText();
        String UserName=username.getText();
        String FPassword=newpass.getText();
        String ComPassword=newcompass.getText();
        
        //if(FPassword == ComPassword){
        try{
            String sql="UPDATE users SET USERNAME='"+UserName+"',PASSWORD=(sha1('"+ComPassword+"')) WHERE ID='"+UserId+"'";
            
            pst=conn.prepareStatement(sql);
            pst.execute();
                        
            JOptionPane.showMessageDialog(this, "Saved Successfull...");
            
            
        
            try{
                Date currentDate = GregorianCalendar.getInstance().getTime();
                DateFormat df = DateFormat.getDateInstance();
                String datestring = df.format(currentDate);
                    
                Date d = new Date ();
                SimpleDateFormat sdf = new SimpleDateFormat ("hh:mm:ss");
                String timestring = sdf.format(d);
                    
                
                String value2 = timestring;
                String value3 = datestring;
                
        
                sql="Insert into audit_tb (User_Id,User_Name,Date,Status)"
                        +"values("+value0+",'"+value1+"','"+value3+" / "+value2+"','"+UserName+"-Chenge Password...')";
                pst=conn.prepareStatement(sql);
                pst.execute();
            
            }catch(Exception e){
            
                //JOptionPane.showMessageDialog(null, e);
            
            }finally{
                try{
                
                    rs.close();
                    pst.close();
                
                }catch(Exception e){
                    //JOptionPane.showMessageDialog(null, e);
                }
            }
            
        }catch(Exception e){
            
            //JOptionPane.showMessageDialog(null, e);
            
        }finally{
            try{
                clearchangess();
                
                rs.close();
                pst.close();
                
            }catch(Exception e){
                //JOptionPane.showMessageDialog(null, e);
            }
        }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        clearchangess();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void UserIddropKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UserIddropKeyReleased
        try{
            
            //users
            String a=UserIddrop.getText();
            String sql="select USERNAME from users where ID="+a+"";
            
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            
            while(rs.next()){
                UserNamedrop.setText(rs.getString("USERNAME"));
            }
            
            
            
        }catch(Exception e){
            
            
            
        }finally{
            try{
                
                rs.close();
                pst.close();
                
            }catch(Exception e){
                
            }
        }
    }//GEN-LAST:event_UserIddropKeyReleased

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       int confirmed = JOptionPane.showConfirmDialog(null, 
        "Are you sure you want to drop this user?", "Drop Program Message Box",
        JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
        try{
            
            //Drop users
            String a=UserIddrop.getText();
            String sql="DELETE FROM users WHERE ID="+a+"";
            
            pst=conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(this, "Droped Successfull...");
            
            
        
            try{
                Date currentDate = GregorianCalendar.getInstance().getTime();
                DateFormat df = DateFormat.getDateInstance();
                String datestring = df.format(currentDate);
                    
                Date d = new Date ();
                SimpleDateFormat sdf = new SimpleDateFormat ("hh:mm:ss");
                String timestring = sdf.format(d);
                
                int value0 = USER.UserId;
                String value1 = USER.UserName;
                String N=UserNamedrop.getText();
                String value2 = timestring;
                String value3 = datestring;
                
        
                sql="Insert into audit_tb (User_Id,User_Name,Date,Status)"
                        +"values("+value0+",'"+value1+"','"+value3+" / "+value2+"','"+N+"-Droped Account...')";
                pst=conn.prepareStatement(sql);
                pst.execute();
            
            }catch(Exception e){
            
                //JOptionPane.showMessageDialog(null, e);
            
            }finally{
                try{
                
                    rs.close();
                    pst.close();
                
                }catch(Exception e){
                    //JOptionPane.showMessageDialog(null, e);
                }
            }
            
        }catch(Exception e){
            
            
            
        }finally{
            try{
                UserIddrop.setText("");
                UserNamedrop.setText("");
                
                rs.close();
                pst.close();
                
            }catch(Exception e){
                
            }
        }        
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        UserIddrop.setText("");
        UserNamedrop.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jLabel20MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MousePressed
        upass.setEchoChar((char)0);
    }//GEN-LAST:event_jLabel20MousePressed

    private void jLabel20MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseReleased
        upass.setEchoChar('*');
    }//GEN-LAST:event_jLabel20MouseReleased

    private void jLabel21MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MousePressed
        ucpass.setEchoChar((char)0);
    }//GEN-LAST:event_jLabel21MousePressed

    private void jLabel21MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseReleased
        ucpass.setEchoChar('*');
    }//GEN-LAST:event_jLabel21MouseReleased

    private void img01MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img01MousePressed
        newpass.setEchoChar((char)0);
    }//GEN-LAST:event_img01MousePressed

    private void img01MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img01MouseReleased
        newpass.setEchoChar('*');
    }//GEN-LAST:event_img01MouseReleased

    private void img2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img2MousePressed
        newcompass.setEchoChar((char)0);
    }//GEN-LAST:event_img2MousePressed

    private void img2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img2MouseReleased
        newcompass.setEchoChar('*');
    }//GEN-LAST:event_img2MouseReleased

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            int value0 = USER.UserId;
        String value1 = USER.UserName;
        String UserName=uname.getText();
        String FPassword=upass.getText();
        String ComPassword=ucpass.getText();
        
        //if(FPassword == ComPassword){
        try{
            String sql="insert into users (USERNAME,PASSWORD)"
                    +"values('"+UserName+"',(sha1('"+ComPassword+"')))";
            
            pst=conn.prepareStatement(sql);
            pst.execute();
                        
            JOptionPane.showMessageDialog(this, "Saved Successfull...");
            
            
        
            try{
                Date currentDate = GregorianCalendar.getInstance().getTime();
                DateFormat df = DateFormat.getDateInstance();
                String datestring = df.format(currentDate);
                    
                Date d = new Date ();
                SimpleDateFormat sdf = new SimpleDateFormat ("hh:mm:ss");
                String timestring = sdf.format(d);
                    
                
                String value2 = timestring;
                String value3 = datestring;
                
        
                sql="Insert into audit_tb (User_Id,User_Name,Date,Status)"
                        +"values("+value0+",'"+UserName+"','"+value3+" / "+value2+"','Create New Account...')";
                pst=conn.prepareStatement(sql);
                pst.execute();
            
            }catch(Exception e){
            
                //JOptionPane.showMessageDialog(null, e);
            
            }finally{
                try{
                
                    rs.close();
                    pst.close();
                
                }catch(Exception e){
                    //JOptionPane.showMessageDialog(null, e);
                }
            }
            
        }catch(Exception e){
            
            //JOptionPane.showMessageDialog(null, e);
            
        }finally{
            try{
                uname.setText("");
                upass.setText("");
                ucpass.setText("");
                
                rs.close();
                pst.close();
                
            }catch(Exception e){
                //JOptionPane.showMessageDialog(null, e);
            }
        }
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton2KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            uname.setText("");
        upass.setText("");
        ucpass.setText("");
        }
    }//GEN-LAST:event_jButton2KeyPressed

    private void jButton3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton3KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            Library_Manegement_System_Administetor windowshow= new Library_Manegement_System_Administetor();
        windowshow.show();
        this.dispose();
        }
    }//GEN-LAST:event_jButton3KeyPressed

    private void jButton4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton4KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            int confirmed = JOptionPane.showConfirmDialog(null, 
        "Are you sure you want to change the password?", "Change Password Program Message Box",
        JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
        int value0 = USER.UserId;
        String value1 = USER.UserName;
        String UserId=usersid.getText();
        String UserName=username.getText();
        String FPassword=newpass.getText();
        String ComPassword=newcompass.getText();
        
        //if(FPassword == ComPassword){
        try{
            String sql="UPDATE users SET USERNAME='"+UserName+"',PASSWORD=(sha1('"+ComPassword+"')) WHERE ID='"+UserId+"'";
            
            pst=conn.prepareStatement(sql);
            pst.execute();
                        
            JOptionPane.showMessageDialog(this, "Saved Successfull...");
            
            
        
            try{
                Date currentDate = GregorianCalendar.getInstance().getTime();
                DateFormat df = DateFormat.getDateInstance();
                String datestring = df.format(currentDate);
                    
                Date d = new Date ();
                SimpleDateFormat sdf = new SimpleDateFormat ("hh:mm:ss");
                String timestring = sdf.format(d);
                    
                
                String value2 = timestring;
                String value3 = datestring;
                
        
                sql="Insert into audit_tb (User_Id,User_Name,Date,Status)"
                        +"values("+value0+",'"+value1+"','"+value3+" / "+value2+"','"+UserName+"-Chenge Password...')";
                pst=conn.prepareStatement(sql);
                pst.execute();
            
            }catch(Exception e){
            
                //JOptionPane.showMessageDialog(null, e);
            
            }finally{
                try{
                
                    rs.close();
                    pst.close();
                
                }catch(Exception e){
                    //JOptionPane.showMessageDialog(null, e);
                }
            }
            
        }catch(Exception e){
            
            //JOptionPane.showMessageDialog(null, e);
            
        }finally{
            try{
                clearchangess();
                
                rs.close();
                pst.close();
                
            }catch(Exception e){
                //JOptionPane.showMessageDialog(null, e);
            }
        }
        }
        }
    }//GEN-LAST:event_jButton4KeyPressed

    private void jButton5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            clearchangess();
        }
    }//GEN-LAST:event_jButton5KeyPressed

    private void jButton6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton6KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            int confirmed = JOptionPane.showConfirmDialog(null, 
        "Are you sure you want to drop this user?", "Drop Program Message Box",
        JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
        try{
            
            //Drop users
            String a=UserIddrop.getText();
            String sql="DELETE FROM users WHERE ID="+a+"";
            
            pst=conn.prepareStatement(sql);
            pst.execute();
            
            JOptionPane.showMessageDialog(this, "Droped Successfull...");
            
            
        
            try{
                Date currentDate = GregorianCalendar.getInstance().getTime();
                DateFormat df = DateFormat.getDateInstance();
                String datestring = df.format(currentDate);
                    
                Date d = new Date ();
                SimpleDateFormat sdf = new SimpleDateFormat ("hh:mm:ss");
                String timestring = sdf.format(d);
                
                int value0 = USER.UserId;
                String value1 = USER.UserName;
                String N=UserNamedrop.getText();
                String value2 = timestring;
                String value3 = datestring;
                
        
                sql="Insert into audit_tb (User_Id,User_Name,Date,Status)"
                        +"values("+value0+",'"+value1+"','"+value3+" / "+value2+"','"+N+"-Droped Account...')";
                pst=conn.prepareStatement(sql);
                pst.execute();
            
            }catch(Exception e){
            
                //JOptionPane.showMessageDialog(null, e);
            
            }finally{
                try{
                
                    rs.close();
                    pst.close();
                
                }catch(Exception e){
                    //JOptionPane.showMessageDialog(null, e);
                }
            }
            
        }catch(Exception e){
            
            
            
        }finally{
            try{
                UserIddrop.setText("");
                UserNamedrop.setText("");
                
                rs.close();
                pst.close();
                
            }catch(Exception e){
                
            }
        }        
        }
        }
    }//GEN-LAST:event_jButton6KeyPressed

    private void jButton7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton7KeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            UserIddrop.setText("");
        UserNamedrop.setText("");
        }
    }//GEN-LAST:event_jButton7KeyPressed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String apptheme=Themecombobox.getSelectedItem().toString();
        try{
            String sql="delete from applicationtheme where ID='1'";
            
            pst=conn.prepareStatement(sql);
            pst.execute();
            
            sql="insert into applicationtheme (ID,Theme_Name)"
                    +"values(1,'"+apptheme+"')";
            
            pst=conn.prepareStatement(sql);
            pst.execute();
                        
            JOptionPane.showMessageDialog(this, "Saved Successfull...");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Alredy Saved...");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Library_Manegement_System_Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Library_Manegement_System_Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Library_Manegement_System_Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Library_Manegement_System_Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Library_Manegement_System_Setting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Themecombobox;
    private javax.swing.JTextField UserIddrop;
    private javax.swing.JTextField UserNamedrop;
    private javax.swing.JLabel img01;
    private javax.swing.JLabel img2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lab_userid;
    private javax.swing.JLabel lab_username;
    private javax.swing.JPasswordField newcompass;
    private javax.swing.JPasswordField newpass;
    private javax.swing.JPasswordField ucpass;
    private javax.swing.JTextField uname;
    private javax.swing.JPasswordField upass;
    private javax.swing.JTextField username;
    private javax.swing.JTextField usersid;
    // End of variables declaration//GEN-END:variables

    private void seticon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("LibraryMS.png")));
    }

    private void clearchangess() {
        username.setText("");
        newpass.setText("");
        newcompass.setText("");
        usersid.setText("");
    }
}
